package com.premaseem.maestro.agent;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Rule-based, offline fallback for {@link AgentStrategy}: no network calls,
 * fully reproducible, used when no LLM is configured (or for demo runs that
 * must not depend on network/API-key availability). It never pretends to
 * produce reviewed production code — every artifact it generates is an
 * explicitly-labeled scaffold, and {@link #assessReleaseReadiness} always
 * discloses that as a risk.
 */
public final class DeterministicAgentStrategy implements AgentStrategy {

    private static final Set<String> CONCRETE_KEYWORDS = Set.of(
            "endpoint", "url", "link", "expire", "expired", "redirect", "code", "api",
            "test", "doc", "analytics", "click", "login", "auth", "qr", "delete", "rate", "limit", "short");

    @Override
    public RequirementAnalysis interpretRequirement(String requirementText) {
        String normalized = requirementText.trim();
        boolean ambiguous = isAmbiguous(normalized);

        List<String> clarifyingQuestions = ambiguous
                ? List.of(
                        "What specific behavior or endpoint should change?",
                        "Which part of the existing shortener does this affect, if any?",
                        "What does success look like — is there an acceptance criterion?")
                : List.of();

        List<String> assumptions = ambiguous
                ? List.of()
                : List.of("Change is scoped to url-shortener-service unless the requirement says otherwise");

        return new RequirementAnalysis(normalized, ambiguous, clarifyingQuestions, assumptions);
    }

    private boolean isAmbiguous(String normalized) {
        String lower = normalized.toLowerCase(Locale.ROOT);
        int wordCount = normalized.split("\\s+").length;
        boolean hasConcreteKeyword = CONCRETE_KEYWORDS.stream().anyMatch(lower::contains);
        return wordCount < 5 || !hasConcreteKeyword;
    }

    @Override
    public DesignProposal design(RequirementAnalysis analysis) {
        String lower = analysis.normalizedProblem().toLowerCase(Locale.ROOT);
        List<String> impactedFiles = new ArrayList<>();

        if (lower.contains("expire")) {
            impactedFiles.add("url-shortener-service/.../domain/ShortUrl.java");
            impactedFiles.add("url-shortener-service/.../service/ShortUrlServiceImpl.java");
        }
        if (lower.contains("redirect") || lower.contains("click")) {
            impactedFiles.add("url-shortener-service/.../web/ShortUrlController.java");
        }
        if (lower.contains("validat")) {
            impactedFiles.add("url-shortener-service/.../web/dto/CreateShortUrlRequest.java");
        }

        boolean brownfield = !impactedFiles.isEmpty();
        String approachSummary = brownfield
                ? "Brownfield change targeting existing shortener code: " + analysis.normalizedProblem()
                : "Greenfield addition to the shortener: " + analysis.normalizedProblem();

        List<Task> tasks = List.of(
                new Task("implement", "Implement: " + analysis.normalizedProblem()),
                new Task("test", "Add unit tests covering happy path and corner cases"),
                new Task("document", "Update documentation for the change"));

        return new DesignProposal(approachSummary, tasks, List.copyOf(impactedFiles));
    }

    @Override
    public CodePatch implement(DesignProposal design) {
        StringBuilder diff = new StringBuilder("// Deterministic scaffold — not reviewed production code\n");
        for (Task task : design.tasks()) {
            diff.append("// TODO(maestro-deterministic): ").append(task.description()).append('\n');
        }

        List<String> touchedFiles = design.impactedFiles().isEmpty()
                ? List.of("(new file — greenfield addition, path to be determined during implementation)")
                : design.impactedFiles();

        return new CodePatch("url-shortener-service", diff.toString(), touchedFiles);
    }

    @Override
    public TestSuite writeTests(CodePatch patch) {
        List<String> testNames = List.of(
                patch.targetModule() + ": happy path scaffold test",
                patch.targetModule() + ": corner case scaffold test");
        return new TestSuite(testNames, "Deterministic scaffold test plan for " + patch.targetModule());
    }

    @Override
    public Documentation writeDocs(CodePatch patch) {
        String content = "## " + patch.targetModule() + " change\n\n"
                + "Touched files: " + String.join(", ", patch.touchedFiles()) + "\n\n"
                + "Generated by Maestro (deterministic strategy) for premaseem.";
        return new Documentation(content);
    }

    @Override
    public ReleaseReadinessReport assessReleaseReadiness(CodePatch patch, TestSuite tests, Documentation docs) {
        List<String> risks = List.of(
                "Deterministic strategy output is a scaffold and has not been reviewed by a human or a real LLM"
                        + " — do not merge without review.",
                "No static analysis or real compilation was run against this patch.");
        return new ReleaseReadinessReport(true, risks,
                "Scaffold generated deterministically for " + patch.targetModule() + "; requires human review before merge.");
    }
}
